/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [
  //   {type: 'autogenerated', dirName: '.'},
  // ],

  // But you can create a sidebar manually

  ProductSidebar: [

    'Contributor',
    
 
  ],

  // SenseCAPSidebar: [
  //   {

  //     type: 'category',
  //     label: 'SenseCAP',
  //     items: [
  //       'Sensor/SenseCAP/Industrial-IoT-SenseCAP-Introduction',

  //       {
  //         type: 'category',
  //         label: 'SenseCAP Node',
  //         items: [
  //           'Sensor/SenseCAP/SenseCAP_Node/Sensecap-LoRaWAN-Gateway-and-Wireless-Sensor-User-Guide',
  //           'Sensor/SenseCAP/SenseCAP_Node/SenseCAP-SOLO-CO2-Sensor',
  //           {
  //             type: 'category',
  //             label: 'SenseCAP A1101',
  //             items: [
  //               'Sensor/SenseCAP/SenseCAP_Node/SenseCAP_A1101/Train-Deploy-AI-Model-A1101',
  //             ],
  //           },
  //           {
  //             type: 'category',
  //             label: 'SenseCAP Weather Station',
  //             items: [
  //               'Sensor/SenseCAP/SenseCAP_Node/SenseCAP_Weather_Station/SenseCAP-One-Series-Meteorological-Sensors',
  //               'Sensor/SenseCAP/SenseCAP_Node/SenseCAP_Weather_Station/ORCH-S4-Weather-Station',
  //             ],
  //           },
  //         ],
  //       },
  //       {
  //         type: 'category',
  //         label: 'SenseCAP Probe',
  //         items: [
  //           'Sensor/SenseCAP/SenseCAP_Probe/Liquid-Level-Sensor',
  //           'Sensor/SenseCAP/SenseCAP_Probe/Water-Leak-Detector',
  //           'Sensor/SenseCAP/SenseCAP_Probe/Industrial-ph-Sensor',
  //           'Sensor/SenseCAP/SenseCAP_Probe/Soil-Moisture-Temperature-EC-Sensor',
  //           'Sensor/SenseCAP/SenseCAP_Probe/Soil-Moisture-Temperature-Sensor',
  //         ],
  //       },
  //       {
  //         type: 'category',
  //         label: 'Accessories',
  //         items: [
  //           'Sensor/SenseCAP/Accessories/Industrial-Grade-Optical-Rain-Gauge-RG-15',
  //           'Sensor/SenseCAP/Accessories/Optical-Rain-Gauge-RG-9',
  //         ],
  //       },
  //       {
  //         type: 'category',
  //         label: 'Extra tutorial / FAQ',
  //         items: [
  //           'Sensor/SenseCAP/Extra_Tutorial_FAQ/Build-LoRaWAN-Sensors-SenseCAP-XIAO-Controller-Data-Logger',
  //         ],
  //       },


  //       {

  //         type: 'category',
  //         label: 'SenseCAP Cloud',
  //         items: [
  //           'Cloud_Chain/SenseCAP_M4/wiki',
  //         ],

  //       },

  //     ],

  //   },
  //   {
  //     type: 'html',
  //     value: `
  //     <style>
  //     .sub_item {
  //       width: 275px;
  //       display:inline-block;
  //       text-align:center;
  //       font-size:20px;
  //       color: #8DC21F;
  //       margin-top: 100px;
  //     }
  //     </style>
  //     <a class="sub_item" href="https://files.seeedstudio.com/wiki/One-Click-Download-PDF/c1ev0ps.github.io-docusaurus_wiki-Network-SenseCAP-Industrial-IoT-SenseCAP-Introduction.pdf" target="_blank"><span>Download PDF 📖</span></a>
  //   `,
  //   },
  // ],
  // CNSidebar: [
  //   {

  //     type: 'category',
  //     label: 'Seeed Studio XIAO 拓展板',
  //     items: [
  //       'zh-CN/Sensor/SeeedStudio_XIAO/SeeedStudio_XIAO_Expansion_board/Seeeduino-XIAO-Expansion-Board',
  //     ]
  //   },
  //   {

  //     type: 'category',
  //     label: 'Seeed Studio XIAO SAMD21',
  //     items: [
  //       'zh-CN/Sensor/SeeedStudio_XIAO/SeeedStudio_XIAO_SAMD21/Seeeduino-XIAO',
  //     ]
  //   },

  // ]

};

module.exports = sidebars;
